- hosts: all
  gather_facts: False
  pre_tasks:
    - name: Installing python
      become: True
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  roles:
    - { role: set-hosts, become: true }
- hosts: master
  roles:
      - { role: setup-nfs, install_role: master, become: True }
      - { role: master-disk, become: True }
      - { role: users, install_role: master, become: True }
- hosts: nodes
  roles:
      - { role: setup-nfs, install_role: node, become: True }
      - { role: local-disk, become: True }
      - { role: users, install_role: node, become: True }
      - { role: set-up-conda, become: True }
      - { role: create-conda-env, conda_env_name: test, conda_env_environment: environment.yml, conda_env_cleanup: True, conda_env_activate_for_login_shell: True, become: True }
