- name: Install NFS common
  apt:
      name: nfs-common
      state: present
  with_items:
      - nfs-common
- name: Mount NFS directories
  mount:
    path: "{{ directory }}"
    opts: auto,nofail,noatime,nolock,intr,tcp,actimeo=1800
    fstype: nfs
    src: "{{ master_host }}:/{{ directory }}"
    state: mounted
