- name: Enable password logins
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: 'PasswordAuthentication no'
      line: 'PasswordAuthentication yes'
- name: Reload sshd config
  service:
      name: sshd
      state: reloaded
- name: Add custom shell for students
  copy:
      src: shell.sh
      dest: /usr/local/bin/shell.sh
      mode: 0755
- name: Create user
  include_tasks: create_user_master.yml
  vars:
      user: "{{ item }}"
  with_items: "{{ users }}"
