---
# main Anaconda download server
anaconda_mirror: https://repo.continuum.io/archive

# version of python (2|3)
anaconda_python_ver: 2

# anaconda version (fixed)
anaconda_ver: '5.1.0'

# anaconda checksums...
# https://repo.continuum.io/archive/
anaconda_checksums:
  Anaconda2-5.1.0-Linux-x86_64.sh: md5:5b1b5784cae93cf696e11e66983d8756
  Anaconda3-5.1.0-Linux-x86_64.sh: md5:966406059cf7ed89cc82eb475ba506e5

# when downloading the anaconda binary it might take a while
# don't let you less great network connection cause the role to falter
anaconda_timeout_seconds: 600

# add the anaconda python onto the front of your path.
# Caveat Emptor: if your OS package manager is python based careful about jamming it
anaconda_make_sys_default: True

anaconda_parent_dir: '/usr/local'
anaconda_link_subdir: anaconda

anaconda_pkg_update: false

# install a a list of packages into the root conda env. please consider using conda envs effectively!
#anaconda_install_packages:
#  - package1
#  - package2

# control the install channels
#anaconda_install_channels: "defaults conda-forge bioconda"
